# This is a configuration file for the config package written
# by RStudio. To use, make sure the package `config` is installed,
# via console:
#
# R > install.packages("config")
#
# Then, you can load within a notebook chunk with `library(config)`.
#
# To use default config settings, simply write `config::get()`.
#
# You can learn more at:
#   https://cran.r-project.org/web/packages/config/vignettes/introduction.html.

# TODO: Hayley you may need to update this default pattern if people plan to inherit it below as their system's pattern
default:
  path:
    data: "/Volumes/CAP/data"
    raw: "rawData"
    combined: "combinedData"
  RDMcsvs: 
    RDM_qualtrics: "RDMallClean_Qualtrics.csv"    
  AXcsvs:
    AX_qualtrics: "AXallClean_Qualtrics.csv"
  EXCLUSIONcsvs:
    RDM_AX_Qual_Phs1exclusion: "allExclusionsPhase1.csv"
    RDM_AX_Qual_Phs2exclusion: "allExclusionsPhase2.csv"
    

# Ari's System User
metis:
  path:
    data: "/Volumes/shlab/Projects/CAP/data"

# Hayley's System User
# user:
  # inherits: default

# Peter's System User
# user:
  # inherits: default

  # Kim's System User
# user:
  # inherits: default
