---
title: 'CAP: RDM analysis'
author: "Hayley Brooks"
date: "5/13/2021"
output: html_document
---

Data set up is taken care of by RDMsteup.R script. 
```{r setup, include=FALSE}
rm(list=ls())

library('config')
config = config::get()


setup_source = file.path(config$code_files$setup_data)
source(setup_source) #, local = knitr::knit_global())

```

Plot an example choice set for the gain-only task
```{r}
plot(rdmGainQualtrics$rdmAlternative[rdmGainQualtrics$subID==1], col=rdmGainQualtrics$rdmGroundEV, pch=16, xlab="trial", ylab="safe ($)", main="Safe amounts across the task\ncolors = levels")

plot(rdmGainQualtrics$rdmRiskyGain[rdmGainQualtrics$subID==1], col=rdmGainQualtrics$rdmGroundEV, pch=16, xlab="trial", ylab="risky gain ($)", main="Risky gain amounts across the task\ncolors = levels")

plot(rdmGainQualtrics$rdmGroundEV[rdmGainQualtrics$subID==1], col=rdmGainQualtrics$rdmGroundEV, pch=16, xlab="trial", ylab="levelor context ($)", main="Context created by shared expected values")


```
 


### Risky decision-making analysis
#### Probability of gambling GAIN ONLY TASK
```{r}
# GROUP LEVEL

Phs1Pgam = mean(rdmGainQualtrics$rdmChoice[rdmGainQualtrics$phase==1], na.rm=T); # phase 1 pgamble = 0.3901198
Phse2Pgam = mean(rdmGainQualtrics$rdmChoice[rdmGainQualtrics$phase==2], na.rm=T); # phase 2 pgamble = 0.3783025
bothPhsPgam = mean(rdmGainQualtrics$rdmChoice[rdmGainQualtrics$subID %in% BothPhsSubIDs], na.rm=T); # pgamble across participants who completed both phase 1 and phase (n=313) = 0.3867135

# 95% CI
# phase 1 (n=518)
me1 = qnorm(.975)*(Phs1Pgam/sqrt(Phs1nSub)); #0.03277965
Phs1Pgam + me1; #0.4134254
Phs1Pgam - me1; #0.3478662

# phase 2 (n=326)
me2 = qnorm(.975)*(Phse2Pgam/sqrt(Phs2nSub)); #0.04032889
Phse2Pgam + me2; #0.4118445
Phse2Pgam - me2; #0.3311867

# phase 1 and phase 2 (n = 313)
me3 = qnorm(.975)*(bothPhsPgam/sqrt(BothPhsnSub)); #0.04192421
bothPhsPgam + me3; #0.4203572
bothPhsPgam - me3; #0.3365088


# INDIVIDUAL LEVEL

# data frame where each row is a participant and there are 6 columns: {subID, day, phase 1, phase 2, both  phases, diffPgam}. If a participant is not included because they did not complete phase 2 or they were excluded, there will be an NaN in the corresponding  column. "diffPgam" is the difference in probability of gambling between two phases if we have that information for a given participant

pGambleSubID = as.data.frame(matrix(data=NA, nrow =nSubB4exclusion, ncol=6, dimnames=list(c(NULL), c("subID", "day", "phs1pgam","phs2pgam","bothPhspgam", "diffPgam"))))

for (s in 1:nSubB4exclusion) {
  
  
  subPhs1 = rdmGainQualtrics[rdmGainQualtrics$subID==subNumB4exclusion[s] & rdmGainQualtrics$phase==1,rdmColumns];
  subPhs2 = rdmGainQualtrics[rdmGainQualtrics$subID==subNumB4exclusion[s] & rdmGainQualtrics$phase==2,rdmColumns];
  subDay = rdmGainQualtrics$day[rdmGainQualtrics$subID==subNumB4exclusion[s]]
  
  pGambleSubID$subID[s] = subNumB4exclusion[s]
  pGambleSubID$day[s] = subDay[1]
  pGambleSubID$phs1pgam[s] = mean(subPhs1$rdmChoice, na.rm=T)
  pGambleSubID$phs2pgam[s] = mean(subPhs2$rdmChoice, na.rm=T)
  pGambleSubID$bothPhspgam[s] = mean(c(subPhs1$rdmChoice, subPhs2$rdmChoice), na.rm=T)
  pGambleSubID$diffPgam[s] = pGambleSubID$phs2pgam[s] - pGambleSubID$phs1pgam[s]
 
};

# plot histogram of the change in risk-taking between phases (diff > 0 = more risk taking phase 1; diff < 0 =more risk taking phase 2; diff = 0, similar risk taking across phases)
summary(pGambleSubID$diffPgam); # mean = -.0112 (indicating generally more risk taking in phase 2)
hist(pGambleSubID$diffPgam, main="Distribution of change in risk taking", xlab="change in risk-taking\n p(gamble phase 1) - p(gamble phase 2)", ylab="number of participants",breaks = 100);


plot(pGambleSubID$phs1pgam, pGambleSubID$phs2pgam, abline(a=0, b=1), xlab="p(gamble phase 1)", ylab="p(gamble phase 2)", main="Risk-taking in both phases (mean in red)");
points(mean(pGambleSubID$phs1pgam,na.rm=T), mean(pGambleSubID$phs2pgam,na.rm=T), col="red", pch=17);


```

#### Simple regressions for risky decision-making GAIN ONLY TASK
```{r}
# these models take a few minutes each
m1phaseDay=glmer(rdmChoice~ 1 + rdmGainSC + rdmSafeSC + rdmGroundEV + phaseRecode + dayOverallSC + (0 + rdmGainSC + rdmSafeSC|subID),data=rdmGainQualtrics,family="binomial", control=glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun=1000000)) );

Summary(m1phaseDay); # AIC = 73516.2

#              Estimate Std. Error z value Pr(>|z|)    
#(Intercept)   -0.46892    0.04361 -10.753  < 2e-16 ***
#rdmGainSC     13.65856    0.60706  22.500  < 2e-16 ***
#rdmSafeSC    -37.95784    1.21530 -31.233  < 2e-16 ***
#rdmGroundEV    0.12255    0.02589   4.734 2.21e-06 ***
#phaseRecode   -0.20388    0.07474  -2.728  0.00637 ** 
#dayOverallSC   0.22000    0.14472   1.520  0.12847  

# less risk taking in phase 2


m1phase=glmer(rdmChoice~ 1 + rdmGainSC + rdmSafeSC + rdmGroundEV + phaseRecode  + (0 + rdmGainSC + rdmSafeSC|subID),data=rdmGainQualtrics,family="binomial", na.action=na.exclude, control=glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun=1000000)) );

Summary(m1phase); # AIC =73516.4
#              Estimate Std. Error z value Pr(>|z|)    
# (Intercept)  -0.41266    0.02299 -17.949  < 2e-16 ***
# rdmGainSC    13.65568    0.61218  22.306  < 2e-16 ***
# rdmSafeSC   -37.95829    1.10180 -34.451  < 2e-16 ***
# rdmGroundEV   0.12271    0.02488   4.932 8.13e-07 ***
# phaseRecode  -0.09491    0.02116  -4.486 7.27e-06 ***


m1stais = glmer(rdmChoice~  1 + rdmGainSC +rdmSafeSC + rdmGroundEV + stai_s_score_scaled + (0 + rdmGainSC + rdmSafeSC|subID), data=rdmGainQualtrics, family="binomial", control=glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun=1000000)) );
# no effect of stais
# AIC = 73317.3

m1stait = glmer(rdmChoice~  1 + rdmGainSC +rdmSafeSC + rdmGroundEV + stai_t_score_scaled + (0 + rdmGainSC + rdmSafeSC|subID), data=rdmGainQualtrics, family="binomial", control=glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun=1000000)) );
# no effect of stait
# AIC = 73318.2 

m1uclal = glmer(rdmChoice~  1 + rdmGainSC +rdmSafeSC + rdmGroundEV + uclal_score_scaled + (0 + rdmGainSC + rdmSafeSC|subID), data=rdmGainQualtrics, family="binomial", control=glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun=1000000)) );
# no effect of uclal
# AIC =  73317.8  

m1pss = glmer(rdmChoice~  1 + rdmGainSC +rdmSafeSC + rdmGroundEV + pss_score_scaled + (0 + rdmGainSC + rdmSafeSC|subID), data=rdmGainQualtrics, family="binomial", control=glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun=1000000)) )
# no effect of pss
# AIC = 73317.8

m1covidrisk = glmer(rdmChoice~  1 + rdmGainSC + rdmSafeSC + rdmGroundEV + covq_PAB_q1_personalRisk_scaledNoNA  + (0 + rdmGainSC + rdmSafeSC|subID), data=rdmGainQualtrics, family="binomial", na.action=na.exclude, control=glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun=1000000)) ); # adding "na.action = na.exclude" retains original row number which we need when pulling out residuals

# AIC = 73465.6
#                                      Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                          -0.08316    0.04824  -1.724   0.0847 .  
# rdmGainSC                            13.64850    0.59595  22.902  < 2e-16 ***
# rdmSafeSC                           -38.02249    1.10598 -34.379  < 2e-16 ***
# rdmGroundEV                           0.12352    0.02482   4.977 6.46e-07 ***
# covq_PAB_q1_personalRisk_scaledNoNA  -0.62479    0.07379  -8.467  < 2e-16 ***


# Affective measures... 
# - No observed effects (at this level) for STAIS, STAIT, UCLA-L or PSS
# - covid risk measure predicts less risk -taking
# model w/ covid risk (AIC = 73465.6) outperforms model with phase and day(AIC = 73516.2) and just phase (AIC =73516.4)

# Should we use covid risk as our model moving forward?

# Get and save predicted values (i.e. residuals)
rdmGainQualtrics$predm1cr = predict(m1covidrisk, type="link"); # residuals from covid risk model
rdmGainQualtrics$predm1phs = predict(m1phase, type="link"); # residuals from m1phse

```

Temporal context + RDM - left off here
```{r}

# using the residuals from the covid risk model ('pred1mcr') for now since it was the best fitting model

mPotcShiftEarn = glmer(rdmChoice ~ 0 + rdmPOC1sc*rdmEarningSC + posShift +  (1|subID), data=rdmGainQualtrics, family="binomial", offset=predm1cr);
# AIC =  67115.6 
#                         Estimate Std. Error z value Pr(>|z|)    
# rdmPOC1sc               0.194549   0.059275   3.282  0.00103 ** 
# rdmEarningSC           -0.047262   0.025171  -1.878  0.06043 .  
# posShift                0.017172   0.004239   4.051 5.11e-05 ***
# rdmPOC1sc:rdmEarningSC -0.381397   0.116458  -3.275  0.00106 ** 

```

Affective measures
```{r}

```

