---
title: "Model fitting for full model PT"
author: "Hayley Brooks"
date: "2022-12-12"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library('config')
config = config::get()



# load the functions
# NEED TO FIX CONFIGURATION FILE
ptFXfull_source = file.path("PTnll_fullModel.R")
ptFXgain_source = file.path("PTnll_gainOnly.R")
ptWrapGain_source = file.path("PTmcapply_gainOnly.R")
ptWrapFull_source = file.path("PTmcapply_fullModel.R")
source(ptFXfull_source)
source(ptFXgain_source)
source(ptWrapGain_source)
source(ptWrapFull_source)

# load packages
library('parallel') # Need to load this so mclapply is an option.
library('tictoc'); # to keep track of time

# load data that includes choices from both tasks
capdata = read.csv(file.path(config$path$combined, config$RDMcsvs$RDMbothTasks_qualtrics))
fullModelPhase1 = capdata[capdata$phase==1,]
fullModelPhase2 = capdata[capdata$phase==2,]


```

```{r define-things-for-estimation}

subID_phase1 = unique(fullModelPhase1$subID)
subID_phase2 = unique(fullModelPhase2$subID)
nSubPhase1 = length(subID_phase1)
nSubPhase2 = length(subID_phase2)


eps = .Machine$double.eps;


ncores = 4; # cores that we will use for estimation (all of them)
niter = 250; #iterations per core


PT_ColumnNames_bothTask = c("subID", "lambda", "rhoGain", "mu","lambda SE","rho SE","mu SE","nLL", "failedOptims");


# Set up data to store maximum likelihood results

#for fitting both tasks
PT_singleSub_bothTasks_results = array(data=NA, dim= c(ncores,length(PT_ColumnNames_bothTask), niter), dimnames = list(c(NULL), PT_ColumnNames_bothTask, (NULL))); #storing data for one person for all the iterations


PT_allSubs_fullPhase1_bestResult = as.data.frame(matrix(nrow=nSubPhase1, ncol = length(PT_ColumnNames_bothTask), dimnames = list(c(NULL), PT_ColumnNames_bothTask))); #best pars each subject, multiple times

PT_allSubs_fullPhase2_bestResult = as.data.frame(matrix(nrow=nSubPhase2, ncol = length(PT_ColumnNames_bothTask), dimnames = list(c(NULL), PT_ColumnNames_bothTask))); #best pars each subject, multiple times


```


```{r, echo=FALSE}
# try one subject/optimize once with gain only task
singleSub= fullModelPhase1[fullModelPhase1$subID==subID_phase1[10],]; #pull out data for subject of choice in gain-only and phase 1
singleSub = singleSub[!is.na(singleSub$rdmChoice),] # we didn't remove missed choices in this dataset, but MLE doesn't like NA as choices so we need to remove the missed choices

initparval = c(.6,.4,.5); #setting initial values for lambda, rho, mu when optim runs once.
output <- optim(initparval,ptLL,data=singleSub,method= "L-BFGS-B", lower=c(.01,.01,.01), upper=c(5,1.3,20),hessian=TRUE);
se = sqrt(diag(solve(output$hessian))); # Calculate the standard error of the parameter we estimate
cat("\nBest-fitting parameter=",output$par," with SE=",se); #show parameters and standard errors
```


```{r}

# Do the fitting for one person a bunch of times for one participant
tic()
outputlist <- mclapply(1:ncores, mc.cores = ncores, function(i) parallel_ptLL(niter,singleSub)); 
toc()

countfailoptims = 0;
for(i in 1:ncores){
  for(j in 1:niter){
    if (typeof(outputlist[[i]][[j]]) == 'list'){ # if outputlist is a list then optim did not fail
      PT_singleSub_bothTasks_results[i,1:3,j] <- outputlist[[i]][[j]]$par
      PT_singleSub_bothTasks_results[i,7,j] <- outputlist[[i]][[j]]$value; # pull out the function values
    } else {
      countfailoptims = countfailoptims + 1}
  }
};

indBest <- which(min(PT_singleSub_bothTasks_results[,7,], na.rm = TRUE)==PT_singleSub_bothTasks_results,arr.ind = T); # get the indices of the single best optimization across the cores & iterations
bestoutput <- outputlist[[indBest[1]]][[indBest[3]]];
if(!any(bestoutput$hessian==0)){
  se = sqrt(diag(solve(bestoutput$hessian))); 
}
cat("\nBest-fitting PT parameter=",bestoutput$par," with SE=",se,"ll = ", bestoutput$value); #show parameters and standard errors

```


Fit each participant in ROUND 1, storing the best iteration for each
```{r}
tic(); # start timer
for (s in 1:nSubPhase1){
  

  countfailoptims = 0;
  #print(c("Subject Number", s), quote=FALSE); #status update: show subject number for current iteration
  cat("\nParticipant Number",subID_phase1[s]);

  
  singleSub = fullModelPhase1[fullModelPhase1$subID==subID_phase1[s],] # get individual participant data
  singleSub = singleSub[!is.na(singleSub$rdmChoice),] # we didn't remove missed choices in this dataset, but MLE doesn't like NA as choices so we need to remove the missed choices

  
  PT_allSubs_fullPhase1_bestResult$subID[s] = subID_phase1[s] # store sub ID in the output dataframe

  
  outputlist <- mclapply(1:ncores, mc.cores = ncores, function(i) parallel_ptLL(niter,singleSub)); 

  
  allvals = array(data=NA,dim=c(ncores,4,niter),dimnames = list(c(NULL),c("lambda", "rho", "mu", "ll"), (NULL))); #place holder for all function values
  
  for(i in 1:ncores){
    for(j in 1:niter){
      if (typeof(outputlist[[i]][[j]]) == 'list'){ # if outputlist is a list, then optim did not fail
        allvals[i,1:3,j] <- outputlist[[i]][[j]]$par
        allvals[i,4,j] <- outputlist[[i]][[j]]$value; # pull out the function value
      } else {
        countfailoptims = countfailoptims + 1;}
    }
  };
  
  PT_allSubs_fullPhase1_bestResult$failedOptims[s] = countfailoptims
  indBest <- which(min(allvals[,4,], na.rm = TRUE)==allvals ,arr.ind = T); # get the indices of the single best optimization across the cores & iterations
  bestoutput <- outputlist[[indBest[1]]][[indBest[3]]];
  
  PT_allSubs_fullPhase1_bestResult[s,2:4] <-bestoutput$par; #pull out output structures for best optim
  
  if(!any(bestoutput$hessian==0)){
    se = sqrt(diag(solve(bestoutput$hessian))); #calculate standard errors for each parameter
    PT_allSubs_fullPhase1_bestResult[s,5:7] <- se;}
  
  
  PT_allSubs_fullPhase1_bestResult[s,8] <-bestoutput$value;
  
  cat("\nBest-fitting PT parameter=",bestoutput$par," with SE=",se,"ll = ", bestoutput$value); #show paramters and standard errors
};
toc();

fileName = file.path(config$path$Rdata, "PT_allSubs_fullModelPhase1.Rdata")
save(PT_allSubs_fullPhase1_bestResult, file = fileName); # save results


```



Fit each participant in ROUND 2, storing the best iteration for each
```{r}
tic(); # start timer
for (s in 1:nSubPhase2){
  

  countfailoptims = 0;
  
  cat("\nParticipant Number",subID_phase2[s]);

  
  singleSub = fullModelPhase2[fullModelPhase2$subID==subID_phase2[s],] # get individual participant data
  singleSub = singleSub[!is.na(singleSub$rdmChoice),] # we didn't remove missed choices in this dataset, but MLE doesn't like NA as choices so we need to remove the missed choices

  
  PT_allSubs_fullPhase2_bestResult$subID[s] = subID_phase2[s] # store sub ID in the output dataframe

  
  outputlist <- mclapply(1:ncores, mc.cores = ncores, function(i) parallel_ptLL(niter,singleSub)); 

  
  allvals = array(data=NA,dim=c(ncores,4,niter),dimnames = list(c(NULL),c("lambda", "rho", "mu", "ll"), (NULL))); #place holder for all function values
  
  for(i in 1:ncores){
    for(j in 1:niter){
      if (typeof(outputlist[[i]][[j]]) == 'list'){ # if outputlist is a list, then optim did not fail
        allvals[i,1:3,j] <- outputlist[[i]][[j]]$par
        allvals[i,4,j] <- outputlist[[i]][[j]]$value; # pull out the function value
      } else {
        countfailoptims = countfailoptims + 1;}
    }
  };
  
  PT_allSubs_fullPhase2_bestResult$failedOptims[s] = countfailoptims
  indBest <- which(min(allvals[,4,], na.rm = TRUE)==allvals ,arr.ind = T); # get the indices of the single best optimization across the cores & iterations
  bestoutput <- outputlist[[indBest[1]]][[indBest[3]]];
  
  PT_allSubs_fullPhase2_bestResult[s,2:4] <-bestoutput$par; #pull out output structures for best optim
  
  if(!any(bestoutput$hessian==0)){
    se = sqrt(diag(solve(bestoutput$hessian))); #calculate standard errors for each parameter
    PT_allSubs_fullPhase2_bestResult[s,5:7] <- se;}
  
  
  PT_allSubs_fullPhase2_bestResult[s,8] <-bestoutput$value;
  
  cat("\nBest-fitting PT parameter=",bestoutput$par," with SE=",se,"ll = ", bestoutput$value); #show paramters and standard errors
};
toc();

fileName = file.path(config$path$Rdata, "PT_allSubs_fullModelPhase2.Rdata")
save(PT_allSubs_fullPhase2_bestResult, file = fileName); # save results


```